name: 'GHATR'
description: 'get github tokens'
author: 'me, brxxn'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  secrets:
    description: 'Secrets to be printed'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'